### ISSUE TITLE
<br> does not work

### ISSUE THREAD

**Issue by tomByrer** [BuilderIO/jsx-lite#67]
`<br>` is [valid HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br)
`<br />` does render correctly though

Thanks for your project; thought about doing this years ago!

**Comment by mandx** [comment]
> `<br>` is [valid HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br)

It is true that `<br>` is valid HTML, however this is a JSX-based framework, (like React and [many](https://preactjs.com/) [others](https://github.com/ryansolid/solid)) so all of the rules of JSX applies (like for example, all "tags" must be closed). Parsing HTML is very difficult in itself, and trying to map its concepts to other JSX-based frameworks is very difficult, while the inverse is actually straightforward.

Why JSX? (from [Solid's documentation](https://github.com/ryansolid/solid/blob/master/documentation/rendering.md#rendering)):
> [...] JSX is a great DSL made for compilation. It has clear syntax, supports TypeScript, works with Babel, supports other tooling like Code Syntax Highlighting and Prettier. It was only pragmatic to use a tool that basically gives you that all for free. As a compiled solution it provides great DX. Why struggle with custom Syntax DSLs when you can use one so widely supported?

More from the [JSX's Draft Spec](https://facebook.github.io/jsx/):
> JSX is an XML-like syntax extension to ECMAScript without any defined semantics. It's NOT intended to be implemented by engines or browsers. It's NOT a proposal to incorporate JSX into the ECMAScript spec itself. It's intended to be used by various preprocessors (transpilers) to transform these tokens into standard ECMAScript.

I hope this gives you an idea on why we use JSX (tooling, developer experience, widely supported, familar, made for transpilation, etc) instead of HTML.
